#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}

git() {
  case "$PWD" in
    "$HOME" | "$HOME/.config" | "$HOME/.config/"*) command git --git-dir="$HOME/personal/dotfiles.git/" --work-tree="$HOME" "$@" ;;
    *) command git "$@" ;;
  esac
}

alias cd="z"
alias ls="eza --group-directories-first"
alias cat="bat"
alias fzf='fzf --preview "bat --color=always --style=numbers --line-range=:500 {}"'
#alias sk='sk --preview "bat --color=always --style=numbers --line-range=:500 {}"'

alias znew='f() { zellij attach --session "$1" || zellij --session "$1"; }; f'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"
	#ls="ls -hN --color=auto --group-directories-first" \

# These common commands are just too long! Abbreviate them.
alias \
	g="git" \
	trem="transmission-remote" \
	p="pacman" \
    open="xdg-open" \

alias \
	lf="lfub" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
  config="git --git-dir=$HOME/personal/dotfiles.git/ --work-tree=$HOME" \
