#!/bin/sh

git clone --bare git@github.com:sunil-sts/dotfiles.git $HOME/personal/dotfiles.git
function config {
   /usr/bin/git --git-dir=$HOME/.cfg/ $@
}
config config --unset core.bare
config config --local core.worktree $HOME
config config --local status.showUntrackedFiles no
mkdir -p .config-backup
config checkout
if [ $? = 0 ]; then
  echo "Checked out config.";
  else
    echo "Backing up pre-existing dot files.";
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;
config checkout
