vim.opt.backup = false
vim.opt.breakindent = true
vim.opt.complete = { ".", "w", "b", "u", "t", "i", "kspell" }
vim.opt.completeopt = { "menuone", "noinsert", "noselect" }
vim.opt.cursorline = false
vim.opt.expandtab = true
vim.opt.fillchars = { fold = " ", eob = " " }
vim.opt.grepformat = "%f:%l:%c:%m"
vim.opt.grepprg = "rg --vimgrep"
vim.opt.hidden = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.list = true
vim.opt.listchars = { trail = "." }
vim.opt.mouse = "a"
vim.opt.nrformats = { "alpha", "octal", "hex", "bin" }
vim.opt.number = true
vim.opt.numberwidth = 4
vim.opt.relativenumber = true
vim.opt.scrolloff = 8
vim.opt.showtabline = 2
vim.opt.shiftround = true
vim.opt.shiftwidth = 2
vim.opt.shortmess = "aToO"
vim.opt.showmode = false
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop = 2
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.termguicolors = true
vim.opt.timeoutlen = 750
vim.opt.undodir = os.getenv("HOME") .. "/.local/share/nvim/undodir"
vim.opt.undofile = true
vim.opt.undolevels = 10000
vim.opt.updatetime = 250
vim.opt.wildmode = { "longest:full" }
vim.opt.wrap = false
vim.opt.winborder = 'single'
